- name: Deploy OTA Package to Device
  env:
    TB_TOKEN: ${{ env.TB_TOKEN }}
    THINGSBOARD_URL: ${{ secrets.THINGSBOARD_URL }}
    DEVICE_ID: "5f680200-a2ca-11ef-8ecc-15f62f1e4cc0"
    TENANT_ID: "68523940-9905-11ef-af50-911365b0425f"
    CUSTOMER_ID: "d36e1d70-a2c9-11ef-8ecc-15f62f1e4cc0"
    DEVICE_NAME: "Panier 1"
    DEVICE_PROFILE_ID: ${{ env.DEVICE_PROFILE_ID }}
    OTA_PACKAGE_ID: ${{ env.OTA_PACKAGE_ID }}
    DEVICE_VERSION: 7
  run: |
    curl -s -X POST "$THINGSBOARD_URL/api/device" \
      -H "X-Authorization: Bearer $TB_TOKEN" \
      -H "Content-Type: application/json" \
      -d '{
            "id": {
              "entityType": "DEVICE",
              "id": "'"${DEVICE_ID}"'"
            },
            "createdTime": 1731617553952,
            "tenantId": {
              "entityType": "TENANT",
              "id": "'"${TENANT_ID}"'"
            },
            "customerId": {
              "entityType": "CUSTOMER",
              "id": "'"${CUSTOMER_ID}"'"
            },
            "name": "'"${DEVICE_NAME}"'",
            "type": "BaskE Panier",
            "label": "POC",
            "deviceProfileId": {
              "entityType": "DEVICE_PROFILE",
              "id": "'"${DEVICE_PROFILE_ID}"'"
            },
            "firmwareId": null,
            "softwareId": {
              "entityType": "OTA_PACKAGE",
              "id": "'"${OTA_PACKAGE_ID}"'"
            },
            "externalId": null,
            "version": "'"${DEVICE_VERSION}"'",
            "customerTitle": "Gerard",
            "customerIsPublic": false,
            "deviceProfileName": "BaskE Panier",
            "active": true,
            "additionalInfo": {
              "gateway": false,
              "overwriteActivityTime": false,
              "description": ""
            },
            "deviceData": {
              "configuration": {
                "type": "DEFAULT"
              },
              "transportConfiguration": {
                "type": "MQTT"
              }
            }
          }'
