name: Deploy OTA Package to ThingsBoard

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      THINGSBOARD_URL: ${{ secrets.THINGSBOARD_URL }}
      TB_USERNAME: ${{ secrets.TB_USERNAME }}
      TB_PASSWORD: ${{ secrets.TB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check ThingsBoard URL
        run: echo "Using ThingsBoard URL $THINGSBOARD_URL"

      - name: Package application for OTA
        run: |
          zip -r ota_package.zip .  # Créez un fichier ZIP contenant le code et les dépendances

      - name: Upload OTA package artifact
        uses: actions/upload-artifact@v3
        with:
          name: ota_package
          path: ota_package.zip

      - name: Get ThingsBoard Token
        id: tb_login
        run: |
          response=$(curl -s -X POST "$THINGSBOARD_URL/api/auth/login" \
            -H "Content-Type: application/json" \
            -d '{"username": "'"$TB_USERNAME"'", "password": "'"$TB_PASSWORD"'"}')
          token=$(echo "$response" | jq -r '.token')
          echo "TB_TOKEN=$token" >> $GITHUB_ENV

      - name: Create OTA Package in ThingsBoard
        env:
          TB_TOKEN: ${{ env.TB_TOKEN }}
        run: |
          response=$(curl -s -X POST "$THINGSBOARD_URL/api/otaPackage" \
            -H "X-Authorization: Bearer $TB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
                  "deviceProfileId": "68c1c3f0-9905-11ef-af50-911365b0425f",
                  "type": "FIRMWARE",
                  "title": "Python et TRT Update",
                  "version": "v1.0.0"
                }')
          ota_package_id=$(echo "$response" | jq -r '.id.id')
          echo "OTA_PACKAGE_ID=$ota_package_id" >> $GITHUB_ENV

      - name: Upload OTA Content
        env:
          TB_TOKEN: ${{ env.TB_TOKEN }}
          OTA_PACKAGE_ID: ${{ env.OTA_PACKAGE_ID }}
        run: |
          # Télécharger le contenu OTA sur ThingsBoard
          curl -X POST "$THINGSBOARD_URL/api/otaPackage/$OTA_PACKAGE_ID/content" \
            -H "X-Authorization: Bearer $TB_TOKEN" \
            -F "file=@ota_package.zip" \
            -H "Content-Type: multipart/form-data"
