name: Flutter CI

on:
  push:
    branches: [ "flutterflow" ]
  pull_request:
    branches: [ "flutterflow" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang cmake ninja-build pkg-config libgtk-3-dev

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Build Linux Desktop
        run: flutter build linux --release

      - name: Upload Linux Desktop artifact
        uses: actions/upload-artifact@v3
        with:
          name: flutter-linux-app
          path: build/linux/x64/release/bundle/*

      # Trigger Main Repository Workflow
      - name: Trigger Main Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: your-org/main-repo
          event-type: trigger-ota
          client-payload: '{"ref": "${{ github.ref_name }}", "repository": "RayaneZ/iot-mobile"}'
